vqgan_ckpt: 'pretrained_models/AutoencoderModel.ckpt'

diffusion_img_size: 16
diffusion_depth_size: 16
diffusion_num_channels: 17
out_dim: 8
dim_mults: [1,2,4,8]
results_folder: checkpoints/ddpm/
results_folder_postfix: 'basic'
load_milestone: False

batch_size: 2 # 40
num_workers: 20
logger: wandb
objective: pred_x0
save_and_sample_every: 1000
denoising_fn: Unet3D
train_lr: 1e-4
timesteps: 100 # number of steps
sampling_timesteps: 250 # number of sampling timesteps (using ddim for faster inference [see citation for ddim paper])
loss_type: l1 # L1 or L2
train_num_steps: 60000 # total training steps
gradient_accumulate_every: 2 # gradient accumulation steps
ema_decay: 0.995 # exponential moving average decay
amp: False # turn on mixed precision
num_sample_rows: 1
gpus: 6
