root_dir: '/mnt/889cdd89-1094-48ae-b221-146ffe543605/gwd/dataset/RecT500'
name: 'prlnmask'
a_min: -175
a_max: 250
b_min: -1.0
b_max: 1.0
space_x: 0.7
space_y: 0.7
space_z: 1.25
roi_x: 64
roi_y: 64
roi_z: 64
batch_size: 4
num_workers: 16
num_samples: 10
check_data_integrity: False
visualize: False
dist: False
diffusion_img_size: 8
diffusion_depth_size: 8
use_sdf: True